### Introduction To Multi-Dimensional Numpy Array In 2020 is Part-II in Series(`Introduction To Numpy In 2020`) By [Turing Institute](https://turinginstitute.in/)

In [1]:
import numpy as np

In [2]:
L = [[1,2,3],
          [4,5,6]]
A = np.array(L)

In [3]:
print(A,type(A),A.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [4]:
L = [1,2,3,4,5,6]
A = np.array(L)

In [5]:
print(A,A.shape)

[1 2 3 4 5 6] (6,)


In [6]:
A = A.reshape((2,3))

In [7]:
print(A,type(A),A.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [8]:
A = np.arange(1,11).reshape((2,5))

In [9]:
print(A,A.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [10]:
print(A[0,2])

3


In [11]:
print(A[1,1:4])

[7 8 9]


In [12]:
print(A[:2,1:4])

[[2 3 4]
 [7 8 9]]


In [13]:
print(A[:,-2:])

[[ 4  5]
 [ 9 10]]


In [14]:
L = A[1,:3]

In [15]:
print(L,type(L),L.shape)

[6 7 8] <class 'numpy.ndarray'> (3,)


In [16]:
L = A[:,1:4]

In [17]:
print(L,type(L),L.shape)

[[2 3 4]
 [7 8 9]] <class 'numpy.ndarray'> (2, 3)
