## [Turing Institute](https://turinginstitute.in/) - Introduction To Numpy In 2020 - Part I

In [1]:
import numpy as np 

In [2]:
A = np.array([1,2,3,4,5])
print(A)

[1 2 3 4 5]


In [3]:
L = [1,2,3,4,5]
print(type(L))
A = np.array(L)
print(A,type(A))

<class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
A = np.arange(5)
print(A,type(A))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [5]:
A = np.arange(0,11,2)
print(A,type(A))

[ 0  2  4  6  8 10] <class 'numpy.ndarray'>


In [6]:
L = [1,2,3,4,5]
A = np.array(L)

In [7]:
print(A[0])

print(A[-1])

print(A[0:3])

print(A[-3:])

1
5
[1 2 3]
[3 4 5]
